hardhat project and contract
shiv8115/Staking-Contract pull request #1
Opened 2023-03-07 08:46 UTC by shiv8115

- create a staking contract with a function stake and withdrawing
- contract maintains a list of white-listed ERC20 tokens that the user can stake and the list is stored using OZ's Enumerable address set
- the white list can be updated by the owner of the contract 
- contract generates a reward token for a user based on how long the user has staked their assets
- contract emit events for staking, withdrawing, and rewarding actions.

2023-03-07 10:40 UTC, TokenTitan requested changes

2023-03-07 10:40 UTC, TokenTitan commented on contracts/RewadToken.sol
> +         _mint(msg.sender, 5000);
Why do you think a hardcoded value of 5000 would be enough? it should be taken as a parameter.
What if we want to mint more?

2023-03-07 10:40 UTC, TokenTitan commented on contracts/Staking.sol
> +    uint256 public constant REWARD_PER_BLOCK = 1; // 1 reward token per 5 blocks
You have named it reward per block, then in comment you have written reward per 5 blocks?

2023-03-07 10:40 UTC, TokenTitan commented on contracts/Staking.sol
> +contract StakingContract is Initializable, AccessControlUpgradeable {
Dont need to use both `Initializable` and `AccessControlUpgradeable` because if you check `AccessControlUpgradeable` imports `Initializable` itself

2023-03-07 10:40 UTC, TokenTitan commented on contracts/Staking.sol
> +    address _rewardToken;
where is visibility specifier? why underscore before the name?

2023-03-07 10:40 UTC, TokenTitan commented on contracts/Staking.sol
> +    }
Modifiers should be define before the functions, check solidity style guide for ordering

2023-03-07 10:40 UTC, TokenTitan commented on contracts/Staking.sol
> +        require(_whitelistedToken.contains(_token),"Token is not whitelisted");
space missing after comma

2023-03-07 10:40 UTC, TokenTitan commented on contracts/Staking.sol
> +    modifier onlyWhitelistedToken(address _token){
space missing between `) {`

2023-03-07 10:40 UTC, TokenTitan commented on contracts/Staking.sol
> +    }
getters are always defined after the main functions and before the internal functions. Check the ordering of functions in solidity style guide.

2023-03-07 10:40 UTC, TokenTitan commented on contracts/Staking.sol
> +    //This function used for staking token of amount value
Comments are a good habit but use `netspec` commenting standard, you can find that in the solidity docs

2023-03-07 10:40 UTC, TokenTitan commented on contracts/Staking.sol
> +        onlyWhitelistedToken(token){
bad indentation, use prettier to fix all this and see how it should look, add it to your practice

2023-03-07 10:40 UTC, TokenTitan commented on contracts/Staking.sol
> +    }
add validations for each input parameter, what if I pass `endtime > starttime`? or what if I pass zero address for `rewardToken`

2023-03-07 10:40 UTC, TokenTitan commented on contracts/Staking.sol
> +    }
Read the assignment carefully , do we want this here?

2023-03-07 10:40 UTC, TokenTitan commented on contracts/Staking.sol
> +        _lastUpdateBlock[msg.sender][token] = block.number;
This is redundant as you just did the same update inside `_updateRewards ` function as well

2023-03-07 10:40 UTC, TokenTitan commented on contracts/Token.sol
> +}
take amount in parameter and add an `owner only` mint function.

2023-03-07 10:40 UTC, TokenTitan commented on contracts/Staking.sol
> +    }
bad indentation
Missing event

2023-03-07 10:40 UTC, TokenTitan commented on contracts/Staking.sol
> +    function earned(address user) public view returns (uint256) {
Why is this public?

2023-03-07 10:40 UTC, TokenTitan commented on contracts/Staking.sol
> +        onlyWhitelistedToken(token){
No need to be public

2023-03-07 12:23 UTC, shiv8115 commented
- I have done changes that mentions in comments

2023-03-09 09:21 UTC, TokenTitan requested changes

2023-03-09 09:21 UTC, TokenTitan commented on contracts/Staking.sol
> +    //This function used for staking token of amount value
You have still not resolved this comment, the comments are still not following the netspec standards.

2023-03-09 09:21 UTC, TokenTitan commented on contracts/Staking.sol
> +    }
Was this a requirement for this contract?

2023-03-09 09:21 UTC, TokenTitan commented on contracts/Staking.sol
> +    function updateBlockAtEnd() external {
You can name this better

2023-03-09 09:21 UTC, TokenTitan commented on contracts/Staking.sol
> +    function updateBlockAtEnd() external {
And what If as an attacker I keep calling this function? because this will repeatedly update the value and hence I will get higher rewards

2023-03-15 04:31 UTC, merged